### ISSUE TITLE
Type inference

### ISSUE THREAD

**Issue by marcus3santos** [kiselgra/c-mera#103]
Could you add a type inference system?

**Comment by kiselgra** [comment]
I'd love to! Do you happen to have some grant money? :)

**Comment by marcus3santos** [comment]
:-)

I just wish I had...

On a similar note, any chances to add support for lambda functions in c-mera, "pro bono"?

**Comment by lispbub** [comment]
Lambda functions are the next item on my list.
I can take a look into it next week :)

**Comment by lispbub** [comment]
Correction:) it was the previous item on the list. We already have support for lambdas. Take a look at the latest commit. You will find test cases that show the syntax and how to use them.
