### ISSUE TITLE
Array initialization using braces

### ISSUE THREAD

**Issue by plops** [kiselgra/c-mera#11]
According to the example in 5.1 of the paper I assumed this would work:
```
(decl ((int a[] (clist 1 2 3))))
```
unfortunately it doesn't emit braces:
```
int a[] = 1, 2, 3;
```

**Comment by jandoerntlein** [comment]
Unfortunately this is due to a fix of cxxgen that improved the C++11 compatibility. If you compile the same example with *cxxgen*, you get
```c++
int a[] { 1, 2, 3 };
```
which is a valid C++11 initializer_list. Seems like the fix that introduced this feature in *cxxgen* broke the clist output in *cgen*.
