### ISSUE TITLE
Typedef doesn't work

### ISSUE THREAD

**Issue by plops** [kiselgra/c-mera#13]
The following both exressions 
```
(typedef (complex float) complex_float)
(typedef complex float complex_float)
```
expands into:
```
itypedef complex floatcomplex_float;
```

I believe the "i" is a typo. There is a whitespace missing between the type and the alias.

**Comment by plops** [comment]
This works:
```
(typedef  |COMPLEX FLOAT| complex_float)
```

**Comment by plops** [comment]
The i still needs to be fixed.

**Comment by kiselgra** [comment]
Yes, this works, but it only uses one symbol (we really want to support separate symbols) and forces you to write your names inverted. Thanks for digging deeper :)

**Comment by lispbub** [comment]
Typedef can only decompose types with known qualifiers, but it is possible to add new ones:
```
(cgen::add-qualifier 'complex)
```

I will add ```add-qualifer``` to the cg-user package and modify the quotation like suggested in issue #14.
