### ISSUE TITLE
Documentation should explain compound types

### ISSUE THREAD

**Issue by plops** [kiselgra/c-mera#14]
I'm having a hard time writing macros that work with compound types that consist of several words like "unsigned int".
Ideally I would like those types to always be written as a list like
(unsigned int).

Casting the return value of malloc is another thing which I can't figure out the correct expression for.
I came up with
```
(simple-print
 (decl ((float
	 (type-pointer a)
	 (cast (pointer float) (funcall malloc (* (funcall sizeof 'float) 3)))))))
```
the expansion of which missses the pointer *
```
float *a = ((float)malloc(sizeof(float) * 3));
```

I would like this
```
(simple-print
 (decl (((float complex)
	 (type-pointer a)
	 (cast (pointer (float complex)) (funcall malloc (* (funcall sizeof '(float complex)) 3)))))))
```
to expand into
```
float complex*a=((float complex*)malloc(sizeof(float complex)*3));
```

**Comment by plops** [comment]
This nearly works:
```
(decl ((|FLOAT COMPLEX|
	 (type-pointer a)
	 (cast |FLOAT COMPLEX*| (funcall malloc (* (funcall sizeof '|FLOAT COMPLEX|) 3))))))
```
```
float complex *a = ((float complex*)malloc(sizeof(float_complex) * 3));
```

**Comment by kiselgra** [comment]
Compound types have a few rough edges, let's see if we can smooth them. At least for the malloc-case the solution is simple, though not general. the following two examples work:
```
(decl ((float *a
              (cast float*
                    (funcall malloc (* (funcall sizeof 'float) 3))))))

(decl ((float* b
               (cast float*
                     (funcall malloc (* (funcall sizeof 'float) 3))))))
```

Our basic notation is as you describe it, e.g. ```(const unsigned long int)``` and this should work for return types and parameters like this:
```
(function foo ((const long int &a)) -> (long long)
  (return a))
```

In declarations our syntax is (intentionally) missing parens, you can say
```
(decl ((const float *a ...)))
```

This does not work in your example as we allow only `valid' qualifiers, which can be added as follows:
```
(cgen:add-qualifier 'complex')
(decl ((complex float *a ...)))
```

I'm not sure why `a-q' is not visible in the cg-user package, and I don't like that it requires quotes (@lispbub: can you have a look at those?). Apart from that this is, sadly, not documented. I'll try to make some time to add a document about those things over the weekend.

However, the cast and sizeof operators do not seem to recognize compund types. @lispbub: can we add this?

**Comment by kiselgra** [comment]
If you wonder why the underscore appears: We try to cater to both, the C programmer (e.g. by supplying ```++```, and ```float *a``` as above) as well as to the Lisp programmer who might not wat to write lots of underscores. Therefore we postprocess the sybols before printing them, converting all characters not part of valid C identifiers to underscores. @lispbub: do we keep track of ambigous symbol names?

**Comment by plops** [comment]
My malloc-creating macro works perfectly with your suggestion. I had to make a single-word alias for the "float complex" type but I can live with that. Now I have a small test program to call using OpenCL and call clFFT to calculate some 2D transforms. 100 Lines of nice Common Lisp Code turn into 300 lines of C with lots of error checking and automatic closing of files and freeing of pointers. This is great, thanks for this software!

**Comment by kiselgra** [comment]
Cool, thanks for giving it a shot, still being beta and all that :)

Would you mind sharing your code? Might make a cool example :)

**Comment by plops** [comment]
I uploaded it here: https://github.com/plops/c-mera-clFFT-example
During development I insist that I can run the code generation interactively. I haven't bothered to automate this. So getting to the C99 code is a bit of mess right now. It involves evaluating several s-expressions in Slime.

**Comment by kiselgra** [comment]
Thanks! We'll test it out and see if we can make the in-emacs workflow simpler.

**Comment by lispbub** [comment]
@kiselgra:
- typedef recognizes compound types and can handle them accordingly, but one must add unknown qualifiers prior.
- indeed, c-mera keeps track of amiguous symbol names. It keeps adding underscores, if an ambiguity occurs.
- i will add a modified version of ```add-qualifier```, which doesn't need quotation to the cg-user package.

The new built-in sizeof function allows compound types without quotation:
```
(sizeof unsigned int)
```
results in:
```
sizeof(unsigned int)
```
But don't forget to add missing qualifiers.
