### ISSUE TITLE
Multiple arguments for comparison

### ISSUE THREAD

**Issue by plops** [kiselgra/c-mera#18]
When the arguments are constant. It is straightforward to write a macro that handles a comparison with multiple arguments:
```
(defmacro m<= (&rest rest)
  `(&& ,@(loop for old-e = nil then e
	    for e in rest
	    when old-e
	    collect `(<= ,old-e ,e))))

example:
(simple-print (decl ((float x 0.5))
		(m<= 0.0 x 1.0)))

expanded:
float x = 0.50000;
(0.00000 <= x) && (x <= 1.00000);
```

If the arguments contain a funcall (with potential side effects) care should be taken to store its value in a temporary variable . If there are multiple arguments with funcall they should be called in a sequence beginning with the first (I guess).

**Comment by kiselgra** [comment]
Not sure if I get the issue, but you are right, this is simple to do :) I think taking care of the side effects is the responsibility of the user. Right now, in stock C-Mera ```(< a b c)``` generates ```(a < b < c)```, which, IMO, is what would be expected, and this is something you should take care about in C as well :)

This works well for stream output in C++ as ```(<< cout a b c)```.

If we wanted to have a more clever scheme, than we would definitely have to check for side effect cases. Is that what you are suggesting, to change the default on this? I think what we have is the same as for C, but if you want to argue against it I'd like to hear it.

**Comment by kiselgra** [comment]
@lispbub @jandoerntlein Do you guys think we should have a special case for this? My take is that ```(< a b c ...)``` might be convenient for ```((a < b) && (b < c) ...)``` (also for ```==```, ```>```, et al.), but then this might be confusing for someone coming from the C side as ```a < b < c``` is valid (but quite unusual).

**Comment by jandoerntlein** [comment]
I agree, the default behavior right now seems to be more appropriate. Coming from C, this is what you would expect. Additionally this is analogous to
```lisp
(+ 1 2 3) => 1 + 2 + 3
(<< cout 1 2 3) => cout << 1 << 2 << 3
(< 1 2 3) => 1 < 2 < 3
```
A special case like @plops suggested is useful but IMO should be clearly seperated (with a special operator symbol) from the standard operators where such a behaviour might not be expected.
As a C programmer you are used to write statements similiar to (and (> 3 1) (not (< 4 1))) anyway :)

**Comment by kiselgra** [comment]
Ok, then I'll close this for now.

**Comment by plops** [comment]
The first answer was enough for me. I wasn't aware that "a < b < c" is a legal C expression and that c-mera's #'< already supports multiple arguments as I know from Common Lisp. I don't think any other macros are necessary at this point.
