### ISSUE TITLE
C-Mera frontend

### ISSUE THREAD

**Issue by kiselgra** [kiselgra/c-mera#19]
A while back we discussed adding a unified frontend that reflects the project's name.

I'd like to have something like

```
$ cmera -c infile -o outfile
$ cmera --[cuda,c++,glsl]
```
We could still keep the other binaries accessible for a more direct invocation, but I think having a frontend might reduce confusion.

Any comments?

**Comment by jandoerntlein** [comment]
+1

**Comment by kiselgra** [comment]
I'll also add this to the documentation, but just for now: You can use the front-end as follows:
```cm {c,c++,cuda,ocl,glsl} <input-file> -o <output-file>```
