### ISSUE TITLE
Escapes

### ISSUE THREAD

**Issue by kiselgra** [kiselgra/c-mera#2]
The example in the Readme (wc -l) shows a bug: The backslash in \n is not taken to the resulting C code.

**Comment by lispbub** [comment]
We already tried to replace the standard escape character "\" with "^", but "^" is already in use for list-processing in the format-command.
Currently it is possible to use "\\n" to get "\n" in the resulting code.
I am not sure if "\\n" or a replacement for "\" is more convenient.

**Comment by kiselgra** [comment]
I think using a different escape character would be even more irritating to newcomers than having to use `\\`. I guess the single `\` is dropped during `read`, is it?

**Comment by kiselgra** [comment]
If I remember correctly, the trouble with that was that it was replacing it everywhere, was it? Can't we hook onto `"` using the reader to only get this for strings?
Or, we could evaluate using `~%` and map it to `\n` during printing, might at least look reasonable to users coming from CL.

What do you think?

**Comment by lispbub** [comment]
I think it should be possible to use the hook onto `"`.

**Comment by kiselgra** [comment]
I belief this is something we will have to live with, simply to avoid meddling with user-strings that might even make it into meta-code...
