### ISSUE TITLE
Don't loose precision of floating point values

### ISSUE THREAD

**Issue by plops** [kiselgra/c-mera#20]
The expression
```
(simple-print (decl ((float a 1.234d-5))))
```
expands into
```
float a = 0.00001;
```
but I would like much more if this was the result:
```
float a = 1.234e-5;
```

**Comment by plops** [comment]
I just changed ast-pretty.lisp
```
(format stream "~,5f" val)
```
into
```
(format stream "~,5e" val)
```
see also
http://www.gigamonkeys.com/book/a-few-format-recipes.html

**Comment by lispbub** [comment]
I was about to suggest the same solution, but perhaps I can find a prettier one.

**Comment by jandoerntlein** [comment]
Something is still broken here:
```lisp
(simple-print (return 0.07))
    return 0.07000
(simple-print (return 0.07f)) ;; float prefix 'f' erases leading zeroes
    return 0.7
```

**Comment by plops** [comment]
I propose you implement it as I suggested before:
```
((floatp val) (format stream "~a" (substitute #\e #\d (format nil "~,8e" val))))
```

It expands into something like this:
9.76562500e-4
while the current code looses precision for small numbers:
0.00098

**Comment by lispbub** [comment]
Hey,

I have adopted your suggested code in c-mera:
```((floatp val) (format stream "~a" (substitute #\e #\d (format nil "~,8e" val))))```
