### ISSUE TITLE
Support for "enums"

### ISSUE THREAD

**Issue by jandoerntlein** [kiselgra/c-mera#3]
The "enum" statement has not been implemented yet.

**Comment by kiselgra** [comment]
@lispbub I think having that would be cool. Note that, for C at least, the name should be optional.

I think of something like this:
```
(enum foo
    val1
    val2
    (val3 20))
```
I wonder how to best distinguish the name from the first constant, maybe using more parens?
```(enum foo (val1 val2 (val3 20)))```?

It should also work with
```
(typedef (enum (val1 val2 (val3 20)))
    my-enum)
```

What do you think?

**Comment by lispbub** [comment]
Enums now supported:

``(enum foo ((val1 4) val2 val3)) `` 
yields
 `` enum foo { val1 = 4, val2, val3 };``


``(typedef (enum ((val1 4) val2 val3)) my-enum)``
yields
 ``typedef enum { val2 = 4, val2, val3 } my-enum;``

With more than 3 elements, the enum declaration spreads over multiple lines
``(enum foo ((val1 1) (val2 2) val3 val3``
yields
```
enum foo {
                   val1 = 1,
                   val2 = 2,
                   val3,
                   val4
};
```
