### ISSUE TITLE
fixed: CCL conditions can hang C-Mera

### ISSUE THREAD

**Issue by kiselgra** [kiselgra/c-mera#49]
When using CCL triggering the condition handler hangs C-Mera. In the following example this is triggered by a bug (see #50), but the general behaviour can be oberserved in other situations, too. Restarts can be selected, but after the handler is done the system hangs. Hitting C-c does not help, so the best exit is to put the job into background-mode and kill it.

```
$ cm -V
> Error: Undefined function c-mera::print-version called with arguments () .
> While executing: cm-c::c-processor, in process toplevel(2).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Retry applying c-mera::print-version to nil.
> Type :? for other options.
1 > :pop
^C^C^C^C^Z
[1]+  Stopped                 cm -V
$ kill cm-c
$ fg
cm -V

Terminated
```

**Comment by lispbub** [comment]
ccl does not hang anymore, but it's only a tentative fix.
