### ISSUE TITLE
Member variables with the same name in different classes

### ISSUE THREAD

**Issue by jandoerntlein** [kiselgra/c-mera#6]
Consider this example:

``` lisp
(class A ()
        (decl ((int value 0))
              (function A () -> ()
                        (set value 4711))))

(class B ()
        (decl ((int value 0))
              (function B () -> ()
                        (set value 42))))
```

The generated output nests the second occurance of 'value' in class 'B' into a seperate block. This behaviour can be bypassed by renaming the variable.

**Comment by jandoerntlein** [comment]
The following example produces invalid code:
``` 
       (private 
        (decl ((int value))
              (public
               (function A () -> ()
                         (set value 4711))))))

(class B ()
       (private
        (decl ((int value))
              (public
               (function B () -> ()
                         (set value 42))))))
```

**Comment by kiselgra** [comment]
Seems like it does not work on all SBCL versions, can you look into that?

**Comment by jandoerntlein** [comment]
Fixed. Reinstalled quicklisp after removing it totally.

**Comment by kiselgra** [comment]
Do you know why this helped?

**Comment by jandoerntlein** [comment]
After reinstalling quicklisp the whole build of c-mera took a lot more time. So I suppose quicklisp (or maybe asdf) cached some build information that can't be deleted with a simple 'make clean' but with the deletion of the entire quicklisp directory.
