### ISSUE TITLE
Nesting of public/protected/private

### ISSUE THREAD

**Issue by kiselgra** [kiselgra/c-mera#62]
The access control forms do not nest properly. That is, with
```
(public foo
  (private bar)
  baz))
```
the member `baz` will be private.

I think we can track that while generating the output-code, can we? @lispbub 
I'll add a test and the assign to you.

**Comment by lispbub** [comment]
Made a tentative fix:
```
(public (dec ((int foo)))
    (private (decl ((int bar))))
    (decl ((int baz))))
```
now yields:
```
public:
   int foo;
private:
   int bar;
public:
   int baz;
```
When access specifiers are nested, the inner specifier repeats the outer specifier on the end of its scope.

Therefore, a little flaw currently remains:
```
(public (dec ((int foo)))
    (private (decl ((int bar))))
    (protected (decl ((int foobar))))
    (decl ((int baz))))
```
results in:
```
public:
   int foo;
private:
   int bar;
public:
protected:
   int foobar;
public:
   int baz;
```

**Comment by kiselgra** [comment]
Looks alright to me for the moment. We should try to get rid of the superfluous specifiers, but imo that is more of an enhancement than fixing a bug. :)
