### ISSUE TITLE
Returning templated-types by reference

### ISSUE THREAD

**Issue by kiselgra** [kiselgra/c-mera#66]
I wanted to generate this piece of code:
```
vector<string>& foo();
```

but it is not straightforward as there is no object to attach the `&` to:

```
(function foo () -> (const (instantiate vector (string)) &))
```

Work-arounds are available, but I think they are not really clean:
```
(function foo () -> (const (instantiate vector (string)) (comment "&" :prefix "")))
(function foo () -> (const (instantiate vector (string)) (addr-of nil)))
```

@lispbub I'm not really sure how a cleaner formulation would look like, maybe
`(reference-to (instantiate ...))`? But this is semantically ambiguous to `(addr-of x)`. Maybe `(reference-type ...)`?

**Comment by lispbub** [comment]
Introducing a ``(reference-type ...)`` is very easy :)

**Comment by lispbub** [comment]
``(postfix& ...`` was already present, but not intended to be used in user code.
``(reference-type ...)`` is now available for that.
Test case has been fixed.
