### ISSUE TITLE
Declaring multiple items of the same type

### ISSUE THREAD

**Issue by kiselgra** [kiselgra/c-mera#70]
Sometimes you need to declare multiple values of the same type. In C this is very convenient:
```
float dir_x, dir_y, dir_z;
```
With C-Mera is is much more verbose as we have to declare those individually:
```
(decl ((float dir-x)
       (float dir-y)
       (float dir-z)))
```

Maybe it would be cool to just pack multiple items in a list:
```
(decl ((float (dir-x dir-y dir-z))))
```

But this will get more compilcated with pointers:
```
(decl ((float (*dir-x dir-y *dir-z))))
```

And even worse with initializers:
```
(decl ((float (dir-x = 0 dir-y dir-z = (foo dir-x)))))
```

An alternative could be to clearly separate the two:
```
(decl ((float (dir-x dir-y dir-z) = (0 _ (foo dir-x)))
```

**Comment by kiselgra** [comment]
Maybe having an explicit list? Such as
```
(decl ((float (list x y z))
       (int (list a = 0 b = 1))))
```

**Comment by lispbub** [comment]
I suggest a specialized version of decl for that case:
```
 (defmacro multi-decl (type vars &body body)
	 `(decl ,(loop for i in vars collect `(,@type ,@i))
	    ,@body))
 ```
which can be mixed with the normal decl if required:

```
(decl ((float x = 1.0f))
  (multi-decl (const int&) ((i = ii) (k = kk))))
```

to get something like:

```
float x = 1.00000000e+0f;
const int& i = ii;
const int& k = kk;
```

But it doesn't seem to be more convenient.

**Comment by kiselgra** [comment]
It is not really more convenient. Looks more like a user-macro that can be easily built on demand.
