### ISSUE TITLE
Having nil in decl

### ISSUE THREAD

**Issue by kiselgra** [kiselgra/c-mera#75]
When generating `decl` forms we might have conditional declarations such as
```
(defmacro my-decls (decls &body body)
  (decl ,(loop for d in decls collect (if (keep d) d))))
```
This works fine, but for the filtered-out declarations a superflous line containing a ';' appears.

This is more easily reproduced by
```
(decl ((int x)
      nil
      (int y))
```

**Comment by lispbub** [comment]
``,(remove nil (loop ... ))`` normally solves that

**Comment by kiselgra** [comment]
Could have thought of that, sorry.

But thanks for the fix :)
