### ISSUE TITLE
goto

### ISSUE THREAD

**Issue by pjstirling** [kiselgra/c-mera#78]
I'm playing with c-mera to see whether it could substitute for an existing application written in sbcl ffi, and I'm trying to implement UNWIND-PROTECT.

How do I inject labels to jump to?

Bonus question: is there a mailing list or IRC channel that would be better to ask this question?

**Comment by lispbub** [comment]
Hey, I'm sorry it was taking so long.
I've added a ``(label <name>)`` statement, and a test-caste for goto-statements.
(A former workaround was to use ``(comment "<name>:" :prefix"")``, but thats not quite elegant) 

@kiselgra Do we have an IRC channel yet? :)

**Comment by kiselgra** [comment]
Hi,

We don't have an IRC channel or mailing list. Our preferred communication channel is via this issue tracker. This way we don't miss entries and can keep track of todos :)

Does lispbub's fix help?

**Comment by pjstirling** [comment]
Yes, that works, perhaps both "comment" and "label" could get added to the README?

**Comment by kiselgra** [comment]
You're right, we should do that. Especially the comment-hack is something people should know. Not because it is nice, but because you can build simple work-arounds for most things.

**Comment by pjstirling** [comment]
After a bit more usage: The label form could do with a tweak to replace hyphens with underscores

**Comment by lispbub** [comment]
Hyphens are now automatically replaced with underscores.
Plain strings are not allowed anymore and require `(cintern (format nil "label"))`
