### ISSUE TITLE
cxxgen with C++11 and OpenMP support

### ISSUE THREAD

**Issue by jandoerntlein** [kiselgra/c-mera#8]
For convenience reasons cxxgen uses the C++11 syntax to declare variables e.g.
```lisp
(for ((int i 0) (< i 10) (set i (+ i 1))
   ...)
``` 
becomes
```c++
for( int i { 0 }; i < 10; i = i + 1 ) 
{...}
```
which is the correct and desired behaviour. But OpenMP does not support this feature - thus when you add "#pragma omp parallel for" prior to the for loop you run into an error like: 
```
error: expected ';' in 'for' statement specifier
    for( int i { 0 }; i < 10; i = i + 1 )
```
Therefore OpenMP is currently not supported at all.

**Comment by jandoerntlein** [comment]
Maybe Clang-OMP (https://clang-omp.github.io/) can deal with this.

**Comment by lispbub** [comment]
Added C++11 syntax exception for declarations in for-loop-heads.
