### ISSUE TITLE
Type macrology

### ISSUE THREAD

**Issue by pjstirling** [kiselgra/c-mera#80]
I'm trying to write a macro that takes a type name as a parameter which then expands to a DECL with a pointer to that type. The macro doesn't control the name of the variable either (so I can't prepend the '*' to its name).

I've tried having the '*' floating free:

`(decl ((,type * ,name)) ...`

But that ends up like `char _ name`

I've also tried using INTERN, and READ-FROM-STRING but they also ended up as underscores.

**Comment by lispbub** [comment]
Try the following:

``(decl (((postfix* ,type) ,name))) ...``
or 
``(decl ((,type (prefix* ,name))) ...``

both yield the same result:
``type* name``

**Comment by pjstirling** [comment]
Did the trick, thanks, something else for the README?

**Comment by kiselgra** [comment]
YES :)

(see my other reply to #82)
