### ISSUE TITLE
Functions confused by struct type names

### ISSUE THREAD

**Issue by pjstirling** [kiselgra/c-mera#81]
peter@laptop-ubuntu:~/Programming/c-mera-test$ cat test.lisp
```lisp
(struct foo ()
	(decl ((int bar))))

(function baz ()
	  -> (struct foo*))
```

peter@laptop-ubuntu:~/Programming/c-mera-test$ cm c++ test.lisp
```c
struct foo
{
	int bar;
};

struct foo*
{
}; baz();
```

**Comment by lispbub** [comment]
The reason for that is, that we allow macros/function in the return form to allow the following:
``(function foo () -> (postfix* int))`` yields ``int* foo ();``

As a side effect `struct` also triggers the macroexpansion:
``(function foo () -> (struct bar))`` results in ``struct bar {}; foo();``

To prevent undesired macro expansion, simply quote `struct`:
``(function foo () -> ('struct bar))`` to get ``struct bar foo();``
