### ISSUE TITLE
Exit status

### ISSUE THREAD

**Issue by pjstirling** [kiselgra/c-mera#83]
I've been using c-mera with make, and an annoyance is that if c-mera aborts it doesn't set the exit status non-zero, which means that make continues on, using the previous generated file causing confusion :disappointed:

**Comment by kiselgra** [comment]
Do you have an example for this?

I just tried to verify but for me it returns non-zero. Use case:
```
$ cat foo.lisp
test
$ cm c foo.lisp
Unhandled unbound-variable in thread #<sb-thread:thread "main thread" running
                                        {10032FE423}>:
  The variable test is unbound.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10032FE423}>
0: (SB-INT:SIMPLE-EVAL-IN-LEXENV TEST #<NULL-LEXENV>)
1: (EVAL TEST)
2: (CM-C::READ-IN-FILE "foo.lisp" :DEBUG #<unused argument>)
3: (CM-C::C-PROCESSOR ("cm-c" "foo.lisp"))
4: ((FLET #:WITHOUT-INTERRUPTS-BODY-90 :IN SB-EXT:SAVE-LISP-AND-DIE))
5: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
$ echo $?
1
```

Did you find a different case that does not return non-zero?

Or does make continue to build files and only fails in the end? I think I have seen this but I also think that's not the way it should be...

**Comment by pjstirling** [comment]
file test2.lisp
```lisp
#+swank
(in-package #:cm-c++)

;; just to demonstrate that there should be some content

(function dummy ()
    -> int
  (return 0))

(error "hi there!")
```

file Makefile
```make
test:
	cm c++ test2.lisp
	clang-format test.cc
```

output from running make:
```
peter@laptop-ubuntu:~/Programming/c-mera-test$ make
cm c++ test2.lisp -o test.cc
hi there!
clang-format test.cc
No such file or directory
Makefile:2: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by pjstirling** [comment]
I was using a version of c-mera built with CCL

**Comment by kiselgra** [comment]
I'll have a look at it by the end of the week, can't make it earlier, sorry! My test was using SBCL, so I'll first try to see if it breaks in both cases.

**Comment by pjstirling** [comment]
It's not that urgent, I already switched back to the sbcl version (which works correctly).

I had experimented with the ccl version to see if it would better help me identify the source of some infinite recursion (it didn't), and forgot to take it out of PATH after I solved that.

**Comment by kiselgra** [comment]
Thanks for the update! Good to know it is a CCL-only problem. @lispbub Can you look into that (I don't have CCL running here atm)?
