### ISSUE TITLE
Varargs

### ISSUE THREAD

**Issue by pjstirling** [kiselgra/c-mera#85]
I need to be able to declare (and define) a function that takes a variable argument list.

Perhaps re-use the &REST symbol as the last element of the parameter list?

```lisp
(function printf ((char* format) &rest) -> int)
```

**Comment by lispbub** [comment]
Here again comes the comment hack in handy:

```
(defun crest () (comment "..." :prefix "" :linebreak nil))

(function test ((int a) (nil (crest)) 
    (return 1))
```

yields:
```
int test (int a, ...)
{
    return 1;
}
```

This is just a quick and dirty hack.
I will take over your proposal and reuse the &REST symbol.
