### ISSUE TITLE
Reader conditionals

### ISSUE THREAD

**Issue by pjstirling** [kiselgra/c-mera#86]
As an experienced lisper, I often use reader conditionals to comment out code that I may want to re-enable later. This mostly works fine in c-mera:

```lisp
(function foo ((int a)
	       #+nil
	       (int b)
	       (int c))
    -> int
  (return 0))
```

```c
int foo(int a, int c)
{
	return 0;
}
```

However, when the reader conditional is for the last element in a list it doesn't work:

```lisp
(function bar ((int a)
	       (int b)
	       #+nil
	       (int c))
    -> int
  (return 0))
```

```
  unmatched close parenthesis

    Line: 33, Column: 16, File-Position: 557

    Stream: #<sb-sys:fd-stream for "file /home/peter/Programming/c-mera-test/test2.lisp" {1002363A03}>
```

**Comment by lispbub** [comment]
The problem with reader conditionals on last list elements should be fixed.

**Comment by pjstirling** [comment]
Looks like it does, thanks!
