### ISSUE TITLE
Large projects

### ISSUE THREAD

**Issue by pjstirling** [kiselgra/c-mera#87]
Another "issue" that really should be a ML post:

My code is now large enough that having all my code in one file is
more than undesirable, which puts me in the land of generating header
files, and source files (Curses on you and all your line, Dennis!).

I'd like to have just the function definitions in one file and then
use that to also produce the header file (so that I don't have to
repeat myself, particularly since I have some macros that generate
lots of functions).

My current "best" way forward is to have a file with keep the
definitions in a file which is then loaded before processing the two
CM files. This file would save the function forms in a special
variable, and then the "header" CM file would have a
(MACROLET ((FUNCTION ...))) run over the SV.

This leads to the rather squicky situation that I now have 3 files
instead of 2, but hopefully you only need to edit 2 of them
occasionally, and most changes only go into the definitions file.

Do you have any better suggestions?

**Comment by kiselgra** [comment]
I have a project with ~10k lines of code across different directories. To make it work (having one file per pair of cpp/h files) I built a small CM library. I'm not totally happy with the process as is, but I could put it online for you to check out. If I have time I'll package it tomorrow, I guess it has proven itself at least a little :)

IMO this is literally an "issue" ;)

**Comment by kiselgra** [comment]
It's still on my list, busy week. Will get to it some time this week!

**Comment by kiselgra** [comment]
Let me know what you think of it once you got to check it out! :)
