### ISSUE TITLE
Virtual destructors

### ISSUE THREAD

**Issue by nihofm** [kiselgra/c-mera#95]
As of right now, I was unable to declare a destructor as virtual, since the function type is implicit.

    (destructor () (delete[] data))

yields:

    Class::~Class() { delete[] data; }

and no further arguments or variations are possible.
Also, I was unable to make the `comment`-hack work.
Maybe have something similar to the  `->`-syntax from `function`?

**Comment by kiselgra** [comment]
You could use

    (function |~Class| () virtual -> nil
      (delete[] data))

for now. This version should also work with a comment-hack, such as

     (function (comment "~foo" :prefix "" :linebreak nil) () virtual -> nil
       (delete[] data))

though I think the first version is more readable.

**Comment by kiselgra** [comment]
The fix is similar to c'tor initializer lists, but consistent with how virtual functions can be specified (see above): if the first body-form of a d'tor is an atom with symbol-name `virtual' then the d'tor will be virtual.

    (destructor
        virtual
        (delete[] data))

See `tests/cxx.class.03.lisp`
