### ISSUE TITLE
C++-style foreach

### ISSUE THREAD

**Issue by nihofm** [kiselgra/c-mera#97]
I couldn't find C++-style foreach loops. I think it would be a nice feature to add. E.g.:
```
for (auto &curr : map)
    add(curr.second);
```
Maybe from something like:
```
(foreach ((const auto &curr) map)
    (add curr.second))
```
It would ease and shorten traversal through stl-containers imo.

**Comment by kiselgra** [comment]
There is `for-each` in cm-c++

    (function foo () -> void
      (for-each (curr map)
        (add curr.second)))
    
    (function foo () -> void
      (for-each (curr map :iterator it)
        (add curr.second)))

This implements the range-based iterator by pre-C++11 syntax:

    void foo()
    {
        for(auto iterator582 = map.begin(); iterator582 != map.end(); ++iterator582) {
            auto curr = *iterator582;
            add(curr.second);
        }
    }
    
    void foo()
    {
        for(auto it = map.begin(); it != map.end(); ++it) {
            auto curr = *it;
            add(curr.second);
        }
    }

Note how you can also give a more sensible name to the iterator-variable.

However, I like your declaration-style syntax and I think we are open to adding a real range-based iterator. What do you think, @lispbub?

**Comment by kiselgra** [comment]
@lispbub: Wouldn't it be simple to check if the `for`form was given 2 arguments and then infer that range-based iteration is to be used?

    (for ((auto &curr) foo.map)
       ...)

Would make one more form differ between C and C++, though. What do you think?
