### ISSUE TITLE
Lambda functions

### ISSUE THREAD

**Issue by nihofm** [kiselgra/c-mera#99]
F.e. using `std::sort` with custom types and/or `std::pair` isn't very straightforward right now.
To map the following code
```
vector<pair<string, uint64_t>> sorted_times(times.begin(), times.end());
sort(sorted_times.begin(), sorted_times.end(),
    [](const pair<string, uint64_t> &a, const pair<string, uint64_t> &b) {
        return b.second < a.second;
    });
```
I had to use a function object
```
(struct cmp_op
  (function |OPERATOR()| ((const (instantiate #:std:pair (string) (uint64_t)) &a) (const (instantiate #:std:pair (string) (uint64_t)) &b)) -> bool
    (return (< a.second b.second))))
(decl (((instantiate #:std:vector ((instantiate #:std:pair (string) (uint64_t)))) (sorted_times (times.begin) (times.end))) (cmp_op custom_cmp))
  (#:std:sort (sorted_times.begin) (sorted_times.end) custom_cmp))
```
which is then expanded as
```
struct cmp_op {
    bool operator()(const std::pair<string, uint64_t> &a, const std::pair<string, uint64_t> &b) {
        return a.second < b.second;
    }
};
std::vector<std::pair<string, uint64_t>> sorted_times(times.begin(), times.end());
cmp_op custom_cmp;
std::sort(sorted_times.begin(), sorted_times.end(), custom_cmp);
```
I think lambda functions are a great feature and support for them would make a great addition.
Also, #46 has relevance here. :)

**Comment by nihofm** [comment]
As a side note, declaring a function object inside of a function cannot be done inside a `(decl ...)`, which feels kinda weird, since the function object is declared for the scope of the function only.

**Comment by kiselgra** [comment]
You mean declaring the struct, right? That has to be separate, yes, not an easy one :)

**Comment by nihofm** [comment]
Yeah exactly, the struct for declaring / defining the function object.
